{% set name = "aiohttp-devtools" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiohttp-devtools-{{ version }}.tar.gz
  sha256: aae66fc9dd36b6c13e1ca381004dfaa4db6ba0dd50764c8ae3a49c1ed43f9587

build:
  entry_points:
    - adev = aiohttp_devtools.cli:cli
    - aiohttp-devtools = aiohttp_devtools.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.8.0
    - click >=6.6
    - python-devtools >=0.6
    - pygments >=2.2.0
    - watchfiles >=0.10

test:
  imports:
    - aiohttp_devtools
  commands:
    - pip check
    - adev --help
    - aiohttp-devtools --help
  requires:
    - pip

about:
  home: https://github.com/aio-libs/aiohttp-devtools
  summary: Dev tools for aiohttp
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
