{% set name = "aiohttp-devtools" %}
{% set version = "1.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiohttp-devtools-{{ version }}.tar.gz
  sha256: f46a87b250a84bf8edca21c8b6991dc2b6145cdf0af8a08b73f5c92d48d85f01

build:
  entry_points:
    - adev = aiohttp_devtools.cli:cli
    - aiohttp-devtools = aiohttp_devtools.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - aiohttp >=3.8.0
    - click >=6.6
    - python-devtools >=0.5
    - pygments >=2.2.0
    - watchgod >=0.2

test:
  imports:
    - aiohttp_devtools
  commands:
    - pip check
    - adev --help
    - aiohttp-devtools --help
  requires:
    - pip

about:
  home: https://github.com/aio-libs/aiohttp-devtools
  summary: Dev tools for aiohttp
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
